name = "NetworkOptions"
uuid = "ca575930-c2e3-43a9-ace4-1e988b2c1908"
authors = ["Stefan Karpinski <stefan@karpinski.org> and contributors"]
version = "1.3.0"

[compat]
julia = "1.12"

[extras]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Logging", "Test"]
